package net.raquezha.devconf.compose.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0060A7)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD2E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001C37)
val md_theme_light_secondary = Color(0xFF336B00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFB2F581)
val md_theme_light_onSecondaryContainer = Color(0xFF0B2000)
val md_theme_light_tertiary = Color(0xFF5F6300)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE4EA73)
val md_theme_light_onTertiaryContainer = Color(0xFF1C1D00)
val md_theme_light_error = Color(0xFF9C4237)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD5)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_outline = Color(0xFF777680)
val md_theme_light_background = Color(0xFFFAFDFC)
val md_theme_light_onBackground = Color(0xFF191C1C)
val md_theme_light_surface = Color(0xFFF7FAF9)
val md_theme_light_onSurface = Color(0xFF191C1C)
val md_theme_light_surfaceVariant = Color(0xFFE3E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)
val md_theme_light_inverseSurface = Color(0xFF2D3131)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F0)
val md_theme_light_inversePrimary = Color(0xFFA1C9FF)
val md_theme_light_surfaceTint = Color(0xFF0060A7)
val md_theme_light_outlineVariant = Color(0xFFC7C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFA1C9FF)
val md_theme_dark_onPrimary = Color(0xFF00325A)
val md_theme_dark_primaryContainer = Color(0xFF004880)
val md_theme_dark_onPrimaryContainer = Color(0xFFD2E4FF)
val md_theme_dark_secondary = Color(0xFF97D868)
val md_theme_dark_onSecondary = Color(0xFF173800)
val md_theme_dark_secondaryContainer = Color(0xFF255100)
val md_theme_dark_onSecondaryContainer = Color(0xFFB2F581)
val md_theme_dark_tertiary = Color(0xFFC8CD5A)
val md_theme_dark_onTertiary = Color(0xFF303300)
val md_theme_dark_tertiaryContainer = Color(0xFF474A00)
val md_theme_dark_onTertiaryContainer = Color(0xFFE4EA73)
val md_theme_dark_error = Color(0xFFFFB4A9)
val md_theme_dark_onError = Color(0xFF5F150F)
val md_theme_dark_errorContainer = Color(0xFF7D2B22)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD5)
val md_theme_dark_outline = Color(0xFF91909A)
val md_theme_dark_background = Color(0xFF191C1C)
val md_theme_dark_onBackground = Color(0xFFE0E3E2)
val md_theme_dark_surface = Color(0xFF101414)
val md_theme_dark_onSurface = Color(0xFFC4C7C6)
val md_theme_dark_surfaceVariant = Color(0xFF46464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C5D0)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E2)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val md_theme_dark_inversePrimary = Color(0xFF0060A7)
val md_theme_dark_surfaceTint = Color(0xFFA1C9FF)
val md_theme_dark_outlineVariant = Color(0xFF46464F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF216FB7)


